### ISSUE TITLE
"Release" build pipeline type results in "404 - Page not found' error.

### ISSUE THREAD

**Issue by taylordevereaux** [asergeev95/AddTagToBuildRelatedTasks#3]
From what I can see in your code you are currently using the `System.TeamFoundationCollectionUrl`  to query the release work items. This works for build but does not work for release.
It seems the DevOps url has been updated and should be formatted as: 

`https://vsrm.dev.azure.com/{organization}/{project}/_apis/release/releases/{releaseId}/workitems`

And for those still on the `visualstudio.com` domain it is formatted as: 

`https://{organization}.vsrm.visualstudio.com/{project}/_apis/Release/releases/{releaseId}/workitems`

Ref: [https://docs.microsoft.com/en-us/rest/api/azure/devops/release/releases/list?view=azure-devops-rest-5.1](https://docs.microsoft.com/en-us/rest/api/azure/devops/release/releases/list?view=azure-devops-rest-5.1)

I have tested those new urls with from two organizations with dev.azure.com and visualstudio.com and they both work.

Another issue that will come from this is that the release query also depends on a new parameter
`baseReleaseId`. Which refers to the most recent successful release. This it to filter the list of work items to only include the ones that were updated/linked since the last release. Without this filter the query will return all work items that have been included in a release to date.

Edit: Found that you can use `System.TeamFoundationServerUri` to get the urls:

`https://vsrm.dev.azure.com/{organization}/`
`https://{organization}.vsrm.visualstudio.com/{project}/`

**Comment by aesergeev-tech** [comment]
@taylordevereaux thanks for issue. 
As mentioned at https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#system-variables
```
System.TeamFoundationCollectionUri | The URI of the team foundation collection. For example: https://dev.azure.com/fabrikamfiber/
```
So for `https://vsrm.dev.azure.com/{organization}/{project}/_apis/release/releases/{releaseId}/workitems`
it should be okay. Is there still a problem?

**Comment by aesergeev-tech** [comment]
@taylordevereaux 
I've changed 
```const collectionUrl = process.env['SYSTEM_TEAMFOUNDATIONSERVERURI'];```
New version is available at marketplace and I've uploaded *.vsix at https://github.com/asergeev95/TagLinkedWorkItemsTask/releases/tag/1.1.0
Try this version and tell if it helps you, I can't test update on Azure DevOps Services

**Comment by paulburz** [comment]
> @taylordevereaux
> I've changed
> `const collectionUrl = process.env['SYSTEM_TEAMFOUNDATIONSERVERURI'];`
> New version is available at marketplace and I've uploaded *.vsix at https://github.com/asergeev95/TagLinkedWorkItemsTask/releases/tag/1.1.0
> Try this version and tell if it helps you, I can't test update on Azure DevOps Services

@asergeev95 Now it's giving a 404 page not found with build tagging.
And on release Pipelines, there is no tag being put on the item...

**Comment by aesergeev-tech** [comment]
@taylordevereaux @burzpaul 
I've tested extension in azure devops services. 
It is still 
```const collectionUrl = process.env['SYSTEM_TEAMFOUNDATIONSERVERURI'];```

I've added some output logs and the result is following. 

**For build pipeline**:
```
Team foundation server uri: https://dev.azure.com/***/
Working on test_project project
SystemVssConnection exists true
Collection work items associated with build from https://dev.azure.com/***//test_project/_apis/build/builds/3/workitems
Collected 1 work items for tagging from build
Updating tags on #1 with test_project area
 
```


**For release pipeline:**
```
2020-03-12T15:57:39.2785126Z Team foundation server uri: https://vsrm.dev.azure.com/***/
2020-03-12T15:57:39.2785746Z Working on test_project project
2020-03-12T15:57:39.2794592Z SystemVssConnection exists true
2020-03-12T15:57:39.2986604Z Collection work items associated with release from https://vsrm.dev.azure.com/***//test_project/_apis/release/releases/5/workitems
2020-03-12T15:57:39.6949241Z Collected 1 work items for tagging from release
2020-03-12T15:57:39.8108927Z Updating tags on #1 with test_project area
```

Please take a note of a little update. 
There are two pick lists: root area and child areas. It is for filtering work items for tagging. If only root area specified, tagging will be applied to all work items from root area; if additionally child area specified it also will be considered. root area is a required field. 

Version 1.1.23 is published to marketplace

**Comment by paulburz** [comment]
@asergeev95 I only get 
2020-03-13T10:19:44.2936788Z ##[section]Starting: Tag Linked Work Items
2020-03-13T10:19:44.3022013Z ================================================================
2020-03-13T10:19:44.8033910Z Team foundation server uri: https://vsrm.dev.azure.com/***/
2020-03-13T10:19:44.8034351Z Working on *** project
2020-03-13T10:19:44.8044839Z SystemVssConnection exists true
2020-03-13T10:19:44.8061881Z Collection work items associated with release from https://vsrm.dev.azure.com/***/***/_apis/release/releases/***/workitems
2020-03-13T10:19:45.2961420Z Collected 1 work items for tagging from release
2020-03-13T10:19:45.4416831Z ##[section]Finishing: Tag Linked Work Items

The tagging...is not performed for some reason.

The other issue was resolved by selecting the root and child area.

**Comment by aesergeev-tech** [comment]
@burzpaul I've just published an update with option whether use or not area filtering. If area filtering doesn't enabled so tagging will be applied to all work items associated with build or release.

![image](https://user-images.githubusercontent.com/26343229/78890272-821be680-7a8f-11ea-919e-05865f6f9614.png)

**Comment by paulburz** [comment]
@asergeev95 Now it's working properly.
From my point of view, you can close this Bug and the other one with area filtering.
And just major bump the next version if anything happens 👍
